# Generated by Django 5.2 on 2026-03-15 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkin',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='habit',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='habit',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
